/**
 * Stroke Simplification Utilities (Slice 17)
 *
 * Implements deterministic point reduction for freehand vector strokes:
 * 1. Radial distance pre-filter (O(N)): eliminates redundant points generated by high-frequency mouse/touch jitter.
 * 2. Ramer-Douglas-Peucker (RDP) algorithm (average O(N log N), worst-case O(N^2)): reduces vertex count
 *    while preserving visual curvature and sharp corners within a specified geometric tolerance.
 * 3. Bounding box computation: calculates tight Axis-Aligned Bounding Box (AABB).
 * 4. Local coordinate normalization: translates world-coordinate vertices into local shape space [x - minX, y - minY].
 */

export interface Point2D {
  x: number;
  y: number;
}

export interface StrokeBoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Calculates perpendicular distance from point P to line segment AB.
 */
function perpendicularDistance(p: Point2D, a: Point2D, b: Point2D): number {
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const lenSq = dx * dx + dy * dy;

  if (lenSq === 0) {
    const distSq = (p.x - a.x) * (p.x - a.x) + (p.y - a.y) * (p.y - a.y);
    return Math.sqrt(distSq);
  }

  // Distance formula from point (x0, y0) to line Ax + By + C = 0:
  // |(y2 - y1)*x0 - (x2 - x1)*y0 + x2*y1 - y2*x1| / sqrt((x2 - x1)^2 + (y2 - y1)^2)
  const numerator = Math.abs(dy * p.x - dx * p.y + b.x * a.y - b.y * a.x);
  return numerator / Math.sqrt(lenSq);
}

/**
 * Ramer-Douglas-Peucker recursive reduction.
 */
function rdpRecursive(pts: Point2D[], epsilon: number): Point2D[] {
  if (pts.length <= 2) {
    return pts;
  }

  const first = pts[0];
  const last = pts[pts.length - 1];

  let maxDist = 0;
  let splitIndex = -1;

  for (let i = 1; i < pts.length - 1; i++) {
    const dist = perpendicularDistance(pts[i], first, last);
    if (dist > maxDist) {
      maxDist = dist;
      splitIndex = i;
    }
  }

  if (maxDist > epsilon && splitIndex !== -1) {
    const left = rdpRecursive(pts.slice(0, splitIndex + 1), epsilon);
    const right = rdpRecursive(pts.slice(splitIndex), epsilon);
    // Combine without duplicate split vertex
    return [...left.slice(0, -1), ...right];
  }

  return [first, last];
}

/**
 * Radial distance filter: drops points within minDistance of previous retained point.
 */
function radialDistanceFilter(pts: Point2D[], minDistance: number): Point2D[] {
  if (pts.length <= 2) {
    return pts;
  }

  const minDistSq = minDistance * minDistance;
  const filtered: Point2D[] = [pts[0]];
  let prev = pts[0];

  for (let i = 1; i < pts.length - 1; i++) {
    const curr = pts[i];
    const dx = curr.x - prev.x;
    const dy = curr.y - prev.y;
    if (dx * dx + dy * dy >= minDistSq) {
      filtered.push(curr);
      prev = curr;
    }
  }

  // Always retain the last point to preserve stroke endpoint
  filtered.push(pts[pts.length - 1]);
  return filtered;
}

/**
 * Simplifies a flat array of coordinates [x0, y0, x1, y1, ...] using radial filtering
 * followed by the Ramer-Douglas-Peucker algorithm.
 *
 * @param points Flat array of coordinate pairs in world space.
 * @param tolerance Epsilon distance threshold for RDP in canvas pixels (default: 1.2).
 * @param minDistance Radial distance threshold in canvas pixels (default: 1.0).
 * @returns Simplified flat array of coordinate pairs.
 */
export function simplifyStroke(
  points: number[],
  tolerance: number = 1.2,
  minDistance: number = 1.0
): number[] {
  if (!points || points.length < 4) {
    return points ? [...points] : [];
  }

  // Convert flat array to Point2D objects
  const rawPoints: Point2D[] = [];
  for (let i = 0; i < points.length; i += 2) {
    const x = points[i];
    const y = points[i + 1];
    if (Number.isFinite(x) && Number.isFinite(y)) {
      rawPoints.push({ x, y });
    }
  }

  if (rawPoints.length < 2) {
    return [...points];
  }

  // Step 1: Fast O(N) radial distance filter
  const radiallyFiltered = radialDistanceFilter(rawPoints, minDistance);

  // Step 2: Ramer-Douglas-Peucker reduction
  const simplified = rdpRecursive(radiallyFiltered, tolerance);

  // Step 3: Convert back to flat array
  const result: number[] = [];
  for (const pt of simplified) {
    result.push(pt.x, pt.y);
  }

  return result;
}

/**
 * Computes Axis-Aligned Bounding Box (AABB) from a flat coordinates array [x0, y0, x1, y1, ...].
 *
 * @param points Flat array of coordinate numbers.
 * @param strokeWidth Optional stroke width to ensure minimum dimensions.
 */
export function computeBoundingBox(
  points: number[],
  strokeWidth: number = 2
): StrokeBoundingBox {
  if (!points || points.length < 2) {
    return { x: 0, y: 0, width: strokeWidth, height: strokeWidth };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  for (let i = 0; i < points.length; i += 2) {
    const x = points[i];
    const y = points[i + 1];
    if (Number.isFinite(x) && Number.isFinite(y)) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }

  if (!Number.isFinite(minX)) {
    return { x: 0, y: 0, width: strokeWidth, height: strokeWidth };
  }

  const rawWidth = maxX - minX;
  const rawHeight = maxY - minY;

  // Ensure logical bounding box has positive dimensions even for single clicks or straight vertical/horizontal lines
  const width = Math.max(rawWidth, strokeWidth, 1);
  const height = Math.max(rawHeight, strokeWidth, 1);

  return {
    x: minX,
    y: minY,
    width,
    height,
  };
}

/**
 * Normalizes world-space coordinate vertices to local shape coordinates relative to [originX, originY].
 *
 * @param points Flat array of world coordinates [wx0, wy0, wx1, wy1, ...].
 * @param originX Bounding box minimum X.
 * @param originY Bounding box minimum Y.
 * @returns Flat array of local coordinates [lx0, ly0, lx1, ly1, ...] where lx = wx - originX.
 */
export function normalizePointsToLocal(
  points: number[],
  originX: number,
  originY: number
): number[] {
  if (!points || points.length === 0) {
    return [];
  }

  const localPoints: number[] = new Array(points.length);
  for (let i = 0; i < points.length; i += 2) {
    localPoints[i] = points[i] - originX;
    localPoints[i + 1] = points[i + 1] - originY;
  }

  return localPoints;
}
